name: Publish Docker image

on:
  release:
    types: [published]
  pull_request:  # Temporary for testing, remove before merge

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        service: [api, ingestion-server, index-worker, analytics]
        include:
          - api:
            context: openverse_api
            file: Dockerfile
          - ingestion-server:
            context: ingestion_server
            file: Dockerfile
          - index-worker:
            context: ingestion_server
            file: Dockerfile_worker
          - analytics:
            context: analytics
            file: Dockerfile
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ingestion-server image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.file }}
          # Re-add github.ref_name
          tags: |
            ghcr.io/wordpress/openverse-${{ matrix.service }}:${{ github.sha }}
            ghcr.io/wordpress/openverse-${{ matrix.service }}:latest
